# Generated by Django 4.0.2 on 2022-02-17 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Description of the Manual', max_length=1000)),
            ],
            options={
                'verbose_name': 'Базовый справочник',
                'verbose_name_plural': 'Базовые справочники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('enable_date', models.DateTimeField(help_text='дата начала действия справочника этой версии', verbose_name='Дата')),
                ('manual_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manual.manualbase')),
            ],
            options={
                'verbose_name': 'Cправочника',
                'verbose_name_plural': 'Cправочников',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('summary', models.TextField(help_text='Description of the Manual', max_length=1000)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manual.manual')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'ordering': ['id'],
            },
        ),
    ]
