# Generated by Django 4.0.2 on 2022-02-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['id'], 'verbose_name': 'Cправочника', 'verbose_name_plural': 'Cправочники'},
        ),
    ]
