# Generated by Django 4.0.2 on 2022-02-16 22:59

from django.db import migrations, models
import manual.serices.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualversion',
            options={'ordering': ['id'], 'verbose_name': 'Версию справочника', 'verbose_name_plural': 'Версии справочников'},
        ),
        migrations.AlterField(
            model_name='manualversion',
            name='version',
            field=models.CharField(max_length=50,),
        ),
    ]
