# Generated by Django 4.0.2 on 2022-02-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_alter_manualversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualversion',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
